### ISSUE TITLE
text_processing.rb Errors and functionality

### ISSUE THREAD

**Issue by YellowSloth** [LinuxMercedes/markovirc#23]
When I run `ruby programs/text_processing.rb` with either no arguments or a number like 10, I get the following error:

`programs/text_processing.rb:36:in 'process_event': wrong number of arguments (0 for 1) (ArgumentError)
        from /home/littleyellowsloth/.gem/ruby/gems/workers-0.5.0/lib/workers/worker.rb:67:in 'start_event_loop'
        from /home/littleyellowsloth/.gem/ruby/gems/workers-0.5.0/lib/workers/worker.rb:10:in 'block in initialize'`

Also, it seems like the tablename is hardcoded and not read from the config (I changed that in both places), and it seems to default to 5 threads instead of the default of 15 in the readme.

I think this is the last thing I need in order to get everything running smoothly!

**Comment by brhoades** [comment]
It previously seems that text_processing was using $ARGV instead of ARGV. Arguments should be read now (fixes threads always being 5).

The workers gem updated and made some dramatic changes which broke backwards compatibility. I've changed a method name which fixed that (5623936).

Finally, text processing will read database from ../config.yml by default, and you can pass it a config if you prefer. 

Let me know if this resolves things for you--- I'll update the README to reflect these changes shortly.

**Comment by YellowSloth** [comment]
Yes this is better, there don't seem to be any errors in that aspect. Though, when it tries to form chains it utterly fails. (Perhaps it is trying to insert into the wrong columns?)

```
[2015/09/15 16:46:12.471] !! ========================================
[2015/09/15 16:46:12.471] !! CHAIN RIGHT
[2015/09/15 16:46:12.472] !! ========================================
[2015/09/15 16:46:12.472] !! New source
[2015/09/15 16:46:12.474] !! Couldn't find textid.   
[2015/09/15 16:46:12.474] !! ========================================
[2015/09/15 16:46:12.475] !! CHAIN LEFT
[2015/09/15 16:46:12.475] !! ========================================
[2015/09/15 16:46:12.475] !! Not new source (textid=)
[2015/09/15 16:46:12.477] !!    ID and nextid query res: []
[2015/09/15 16:46:12.477] !! Chain terminated
[2015/09/15 16:46:12.478] !! Penalty added for being below the word limit, now: 31
[2015/09/15 16:46:12.478] !! Penalty calculated: 31
[2015/09/15 16:46:12.480] !! ========================================
[2015/09/15 16:46:12.480] !! CHAIN RIGHT
[2015/09/15 16:46:12.481] !! ========================================
[2015/09/15 16:46:12.481] !! New source
[2015/09/15 16:46:12.483] !! Couldn't find textid.
[2015/09/15 16:46:12.483] !! ========================================
[2015/09/15 16:46:12.484] !! CHAIN LEFT
[2015/09/15 16:46:12.484] !! ========================================
[2015/09/15 16:46:12.484] !! Not new source (textid=)
[2015/09/15 16:46:12.486] !!    ID and nextid query res: []
[2015/09/15 16:46:12.486] !! Chain terminated
[2015/09/15 16:46:12.488] !! ========================================
[2015/09/15 16:46:12.489] !! CHAIN RIGHT
[2015/09/15 16:46:12.489] !! ========================================
[2015/09/15 16:46:12.490] !! New source
[2015/09/15 16:46:12.491] !! Couldn't find textid.
[2015/09/15 16:46:12.492] !! ========================================
[2015/09/15 16:46:12.492] !! CHAIN LEFT
[2015/09/15 16:46:12.492] !! ========================================
[2015/09/15 16:46:12.493] !! Not new source (textid=)
[2015/09/15 16:46:12.494] !!    ID and nextid query res: []
[2015/09/15 16:46:12.495] !! Chain terminated
[2015/09/15 16:46:12.497] !! ========================================
[2015/09/15 16:46:12.497] !! CHAIN RIGHT
[2015/09/15 16:46:12.497] !! ========================================
[2015/09/15 16:46:12.498] !! New source
[2015/09/15 16:46:12.500] !! Couldn't find textid.
[2015/09/15 16:46:12.500] !! ========================================
[2015/09/15 16:46:12.500] !! CHAIN LEFT
[2015/09/15 16:46:12.501] !! ========================================
[2015/09/15 16:46:12.501] !! Not new source (textid=)
[2015/09/15 16:46:12.502] !!    ID and nextid query res: []
[2015/09/15 16:46:12.503] !! Chain terminated
[2015/09/15 16:46:12.505] !! ========================================
[2015/09/15 16:46:12.505] !! CHAIN RIGHT
[2015/09/15 16:46:12.506] !! ========================================
[2015/09/15 16:46:12.506] !! New source
[2015/09/15 16:46:12.508] !! Couldn't find textid.
[2015/09/15 16:46:12.508] !! ========================================
[2015/09/15 16:46:12.509] !! CHAIN LEFT
[2015/09/15 16:46:12.509] !! ========================================
[2015/09/15 16:46:12.509] !! Not new source (textid=)
[2015/09/15 16:46:12.511] !!    ID and nextid query res: []
[2015/09/15 16:46:12.511] !! Chain terminated
[2015/09/15 16:46:12.513] !! ========================================
[2015/09/15 16:46:12.513] !! CHAIN RIGHT
[2015/09/15 16:46:12.514] !! ========================================
[2015/09/15 16:46:12.514] !! New source
[2015/09/15 16:46:12.516] !! Couldn't find textid.
[2015/09/15 16:46:12.516] !! ========================================
[2015/09/15 16:46:12.517] !! CHAIN LEFT
[2015/09/15 16:46:12.517] !! ========================================
[2015/09/15 16:46:12.517] !! Not new source (textid=)
[2015/09/15 16:46:12.519] !!    ID and nextid query res: []
[2015/09/15 16:46:12.519] !! Chain terminated
[2015/09/15 16:46:12.521] !! ========================================
[2015/09/15 16:46:12.522] !! CHAIN RIGHT
[2015/09/15 16:46:12.522] !! ========================================
[2015/09/15 16:46:12.522] !! New source
[2015/09/15 16:46:12.524] !! Couldn't find textid.
[2015/09/15 16:46:12.525] !! ========================================
[2015/09/15 16:46:12.525] !! CHAIN LEFT
[2015/09/15 16:46:12.525] !! ========================================
[2015/09/15 16:46:12.526] !! Not new source (textid=)
[2015/09/15 16:46:12.527] !!    ID and nextid query res: []
[2015/09/15 16:46:12.527] !! Chain terminated
[2015/09/15 16:46:12.529] !! [Thread done] For #<Cinch::Handler @event=:message pattern=#<Cinch::Pattern:0x0000000265e9e0 @prefix=/^!/, @pattern=/say (.+)/, @suffix=nil>>: #<Thread:0x00000002a06f48> -- 0 remaining.
[2015/09/15 16:46:12.530] << PRIVMSG #channel :say
```

Where the bot only replies with "say" in the channel.

**Comment by brhoades** [comment]
Oh interesting. Did you update the database schema to the latest one I updated last night? The one in base/db.sql was correct until a few months ago, when I reverted to an older schema. Try deleting your database and reimporting from:

https://github.com/LinuxMercedes/markovirc/blob/master/base/db.sql

Let me know if that fixes it, please.

**Comment by YellowSloth** [comment]
I'll have to let it repopulate a bit, so I'll check back later today. I have years worth of logs though, ZNC style, that would be great if I could just get it in.

Is there a way to gracefully exit the bot? Ctrl-c isn't escaped currently, making it show an error. It would be nice if the IRC lines would be closed with the proper commands.

Perhaps also add a trigger so you can rehash the config without having to restart the bot and the IRC connections? (I could create separate issues for these things if you want with more detail.) Like I want to allow/disallow it to speak in certain channels.

Many thanks so far, you've been great so far! :)

**Comment by brhoades** [comment]
Yes, let me know how rehashing goes. Sorry for changing the schema on you--- I didn't know anyone was even paying attention to this project :D.

There are currently no ways to gracefully exit--- no. Yes, please create a separate issue for rehashing / graceful exiting. Rehashing I've looked into in the past, and since I could never do it "fully" (like changing database connections and server connections) I never did it. I can still investigate some other avenues.

Oh, allowing/disallowing speech is support for certain channels. The example config shows some options at the very bottom.

**Comment by YellowSloth** [comment]
Hmm I've just let it accumulate a hundred lines and tried running it, this is the result:

```
[17:57] <yellowsloth> little-yellowsloth: test
[17:58] <yellowsloth> little-yellowsloth: say something
[17:58] <little-yellowsloth> something
[17:58] <yellowsloth> little-yellowsloth: don't be a wiseass
[17:58] <little-yellowsloth> don't
[17:58] <yellowsloth> little-yellowsloth: okay reporting this bug
```

Not what I was expecting. Also it can't find chains like before (couldn't find textid=)

Text processing seems to have no effect either currently, it just runs but no changes in the database.

**Comment by YellowSloth** [comment]
Never mind, with just one argument it didn't set the $threads. Fixing that it processes all the data as expected.

**Comment by brhoades** [comment]
Odd, I'm guessing that was running it like:

    ruby text_processing.rb ../configname.yml

That should have set a default thread count, if not that needs to be fixed.
----

Additionally, Marko echos back single chains sometimes when he has nothing to base text off of. This problem disappears with a sufficiently large database (say, > 5k chains). 

Please let me know if he behaves as expected now.

**Comment by YellowSloth** [comment]
Yea I'm already reaching 10k chains by now. It only appears to speak unwantedly, I've got -speak and highlight yet it speaks at random intervals.

Otherwise it's running great now. Already making comprehensible phrases within a couple hours.

**Comment by brhoades** [comment]
Wonderful. If you can open an issue about -speak not blocking random speech, I'd appreciate it. - silent will definitely work, but he won't respond to anything then (including commands).

I'll mark this as resolved.
